
import { SyncData } from "../types";

/**
 * JSONBin.io v3 Integration (Private Mode)
 * This service uses the provided Master Key to create and manage 
 * private bins, ensuring data privacy and security.
 */
const JSONBIN_API_BASE = "https://api.jsonbin.io/v3/b";
const MASTER_KEY = "$2a$10$UDkVQcUTb9K75p2Xf6rO1u6Ytn.lxwZVSkFN49vHZKO3.trLqSWY2";

export const syncService = {
  /**
   * Pushes local data to a JSONBin.
   * Uses X-Master-Key for authentication and sets bins to private.
   */
  async push(key: string, data: SyncData): Promise<string | null> {
    try {
      const isNew = !key;
      const url = isNew ? JSONBIN_API_BASE : `${JSONBIN_API_BASE}/${key}`;
      const method = isNew ? 'POST' : 'PUT';

      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
        'X-Master-Key': MASTER_KEY,
      };

      // When creating a new bin, we explicitly set it to private
      if (isNew) {
        headers['X-Bin-Private'] = 'true';
        headers['X-Bin-Name'] = `TinySteps_${data.babyName || 'Baby'}_${Date.now()}`;
      }

      const response = await fetch(url, {
        method,
        headers,
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`JSONBin push failed (${response.status}): ${errorText}`);
        return null;
      }

      const result = await response.json();
      // For POST, ID is in metadata.id. For PUT, we return the existing key.
      return isNew ? result.metadata.id : key;
    } catch (error) {
      console.error("JSONBin push failed:", error);
      return null;
    }
  },

  /**
   * Pulls data from a private JSONBin using the Bin ID and Master Key.
   */
  async pull(key: string): Promise<SyncData | null> {
    if (!key) return null;
    try {
      const response = await fetch(`${JSONBIN_API_BASE}/${key}/latest`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'X-Master-Key': MASTER_KEY,
        },
      });

      if (!response.ok) {
        console.error(`JSONBin pull failed (${response.status})`);
        return null;
      }

      const result = await response.json();
      return result.record as SyncData;
    } catch (error) {
      console.error("JSONBin pull failed:", error);
      return null;
    }
  },

  /**
   * IDs are generated by JSONBin on the first push.
   */
  generateKey(): string {
    return "";
  }
};
