
import { SyncData } from "../types";

/**
 * JSONBin.io v3 Integration (Public Mode)
 * We use JSONBin in public mode so no Master Key is required.
 * This avoids 401 errors when the environment's API_KEY (Gemini) 
 * is incorrectly passed as a JSONBin Master Key.
 */
const JSONBIN_API_BASE = "https://api.jsonbin.io/v3/b";

export const syncService = {
  /**
   * Pushes local data to a JSONBin.
   * If a key (Bin ID) exists, it updates that public bin.
   * If not, it creates a new public bin and returns its ID.
   */
  async push(key: string, data: SyncData): Promise<string | null> {
    try {
      const isNew = !key;
      const url = isNew ? JSONBIN_API_BASE : `${JSONBIN_API_BASE}/${key}`;
      const method = isNew ? 'POST' : 'PUT';

      const headers: Record<string, string> = {
        'Content-Type': 'application/json',
      };

      // When creating a new bin, we make it public so it can be updated without a key
      if (isNew) {
        headers['X-Bin-Private'] = 'false';
        headers['X-Bin-Name'] = `TinySteps_${data.babyName || 'Baby'}_${Date.now()}`;
      }

      const response = await fetch(url, {
        method,
        headers,
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`JSONBin push failed (${response.status}): ${errorText}`);
        return null;
      }

      const result = await response.json();
      // For POST (new bin), the ID is in metadata.id. For PUT (update), we return the existing key.
      return isNew ? result.metadata.id : key;
    } catch (error) {
      console.error("JSONBin push failed:", error);
      return null;
    }
  },

  /**
   * Pulls data from a public JSONBin using the Bin ID.
   */
  async pull(key: string): Promise<SyncData | null> {
    if (!key) return null;
    try {
      // Public bins can be read without a Master Key
      const response = await fetch(`${JSONBIN_API_BASE}/${key}/latest`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        console.error(`JSONBin pull failed (${response.status})`);
        return null;
      }

      const result = await response.json();
      // JSONBin v3 returns the data inside a 'record' property
      return result.record as SyncData;
    } catch (error) {
      console.error("JSONBin pull failed:", error);
      return null;
    }
  },

  /**
   * Generates a placeholder for interface compatibility.
   * IDs are generated by JSONBin on the first push.
   */
  generateKey(): string {
    return "";
  }
};
